### PR TITLE
Workflow common modifications

### PR DESCRIPTION
**Pull request by ChabbyTMD**
In this PR;

- Main workflow tidied up to follow Snakemake best practices.
- Added activation control in configuration file.
- Modified BgZipTabixMerge to have its output match the input in common.smk.
- Added `.gitignore` to not track specific files and directories.
- Added conditional logic and defined unified input function for rule all in common.smk.

### CODE REVIEW

**Comment by ChabbyTMD** [comment]
Hi Sanjay,

Is it possible the CI checks are failing because there isn't any .fastq.gz data the pipeline needs to execute?

Please advise.

**Comment by ChabbyTMD** [comment]
> Hi Sanjay,
> 
> Is it possible the CI checks are failing because there isn't any .fastq.gz data the pipeline needs to execute?
> 
> Please advise.

Well, this is a facepalm moment 😅. Turns out I had forgotten to update the .test/ config file, that's why the CI checks were failing. It didn't have the up-to-date config options.

**Review by sanjaynagi — APPROVED** [review]
Thanks so much Trevor, this is awesome!! All looks great to me. I will merge in a second. 

p.s  I told you you'd forget to update the .test folder! :D always happens !

**Comment by ChabbyTMD** [comment]
Surely I was warned 😅 I guess it happens to the best of us.

**Pull request merged**
