### PR TITLE
Private webpage 24 04 23

### PR DESCRIPTION
**Pull request by ChabbyTMD**
#16 
Added functionality to create jupyterbook webpage with alignment results.

### CODE REVIEW

**Comment by sanjaynagi** [comment]
Hey @ChabbyTMD, I've just pushed those minor changes back. I also renamed the `private_webpage.smk` to `jupyter-book.smk`, also removed the underscores to become hyphens in the other rule files, hope that's cool.

**Comment by ChabbyTMD** [comment]
Yes this is fine by me.

**Comment by sanjaynagi** [comment]
To get around the CI error, ive added a line to the github action, which copies the docs/ directory into the .tests/ folder prior to running CI. 

I wanted to avoid just copying it into the .tests/ folder generally, as it would increase the size of the directory and we would be duplicating code, and would need to keep doing that each time we edit the ampseeker-book.

**Comment by sanjaynagi** [comment]
@ChabbyTMD @eddUG Going to merge so I can add the coverage notebook.

Fantastic to have this first implementation of the jupyter-book.

**Pull request merged**
