### PR TITLE
Coverage notebook

### LINKED ISSUE #30: Implement coverage notebook
- papermill / nb style 
- Coverage at each amplicon
- Coverage at each SNP

### PR DESCRIPTION
**Pull request by sanjaynagi**
In this PR, we add a coverage notebook, which takes the mosdepth output for each sample, and plots total coverage across the whole genome, as well as coverage at SNP targets. 

Will resolve #30. 

I've had to slightly modify the Bed file we use to add a couple of columns of info. Its difficult, as usually bed files have no column headers, so Im not sure what the best approach is here. 

This also means that the CI isn't going to work. The CI is currently based on the amplicon only reference, and I think we should change this, and instead subset to say the first quarter of chromosomal arm 2L, and add some read data only from that region. 

Theres now a snakemake command --generate-unit-tests, which i may try and use for this.

### CODE REVIEW

**Comment by sanjaynagi** [comment]
also resolves #33

**Comment by sanjaynagi** [comment]
Ok @ChabbyTMD , now that we are no longer going down the amplicon only reference route, I have changed the test case for the CI. 

Now we use a reference which is the beginning of chromosomal arm 2L:2000000-3000000, where we have a lot of amplicon targets in our data. It seems to work. Only now I've done it, I cant figure out if it was fully necessary, but nevermind. I think it was.

**Comment by ChabbyTMD** [comment]
This is really brilliant Sanjay. Yes going forward it's definitely better to have test data that is more akin to what the workflow will be used for and the subsected chromosome 2L will do very nicely as a test case. I'll definitely have to look up the `--generate-unit-test ` Snakemake feature.

The bed file issue will definitely need some brainstorming.

**Comment by sanjaynagi** [comment]
> The bed file issue will definitely need some brainstorming. I looked this [up](https://www.ensembl.org/info/website/upload/bed.html#optional) and it seems that bed files already have designated info that goes into the other fields. So maybe we could put that additional info in some kind of pseudo-metadata file that we can call with an awk script or something idk.

Good point. I agree, I think then we have one input panel metadata file which can be a `.tsv`, and consists of `chrom`, `start`, `end` plus whatever extra columns we want. Then for the variant calling, we do some shell command to remove the column headers before passing that file (which is now basically a .bed) to samtools mpileup. I have already renamed the config input to `targets` rather than `bed` which is good.

Merging now.

**Pull request merged**
